# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: local
    hooks:
      - id: reuse
        name: reuse
        entry: uv run --frozen reuse lint
        language: system
        pass_filenames: false
      - id: ruff-check
        name: ruff-check
        entry: uv run --frozen ruff check --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: uv run --frozen ruff format
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: uv run --frozen mypy
        language: system
        pass_filenames: false
      - id: pytest_unit
        name: pytest-Unit
        entry: uv run --frozen pytest tests/unit
        language: system
        pass_filenames: false
        always_run: true
      - id: pytest_valid
        name: pytest-Validation
        entry: uv run --frozen pytest tests/validation --no-cov
        language: system
        pass_filenames: false
        always_run: true
