#ifndef VNF_PGM_CONVERTER_H
#define VNF_PGM_CONVERTER_H

#ifndef PGM_DLL_EXPORTS
#define PGM_DLL_EXPORTS
#endif

class PgmVnfConverter {
    public:
        // Public attributes
        char* f_file_buffer;
        PGM_dataset_writable_* deserialized_data; // this type because it is generated by a deserializer type structure

        // input data
        // will be supplied by the user:
        // ConstDatasetPtr const unique_input_dataset{PGM_create_dataset_const(hl, "input", 0, 1)};
        // PGM_ConstDataset* input_dataset = unique_input_dataset.get();
        // PGM_dataset_const_* pgm_input_data;

        // Public member functions
        void parse_vnf_file();
        PGM_dataset_const_* convert_input();

    private:
        // Private member functions
        void convert_node_input();
        void convert_line_input();
        void convert_sources_input();
        void convert_sym_loads_input();
        void convert_shunts_input();
        void convert_transformer_input();
        void convert_sym_gens_input();
        void convert_links_input();
};

#endif // VNF_PGM_CONVERTER_H