# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0
---
grid:
  Nodes:
    node:
      id: Number
      u_rated: Unom
      extra: ID
  Cables:
    line:
      id: Number
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
      r1: 'Cables!R[Shortname=Type short]'
      x1: 'Cables!X[Shortname=Type short]'
      c1: 'Cables!C[Shortname=Type short]'
      tan1: 'Cables!Tan_delta[Shortname=Type short]'
      r0: 'Cables!R0[Shortname=Type short]'
      x0: 'Cables!X0[Shortname=Type short]'
      c0: 'Cables!C0[Shortname=Type short]'
#      tan0: Tan_delta  # is dit ook tan_Delta? Gaia expert?
      i_n: Inom'
      extra:
        - Name
        - ID
#  Links:
#    link:
#      id: Number
#      from_node: From.Number
#      from_status: From.Switch state
#      to_node: To.Number
#      to_status: To.Switch state
#
#  Transformers:
#    transformer:
#      id: Number
#      from_node: From.Number
#      from_status: From.Switch state
#      to_node: To.Number
#      to_status: To.Switch state
#      u1: Unom1
#      u2: Unom2
#      sn: Snom    # Cross reference Type r 47 tm 49
#      uk: uk
#      pk: Pk
#
#      i0:
#        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
#          - Inul    # cross reference type r53 tm 55
#          - Pnul
#          - Snom
#          - Unom2
#      p0: Pnul
#      winding_from:
#        power_grid_model.conversion.filters.get_winding_from:
#          - s1  # cross reference type
#          - N1                                 #Navragen bij Gaia expert
#      winding_to:
#        power_grid_model.conversion.filters.get_winding_to:
#          - s2  # cross reference type
#          - N2                                #Navragen bij Gaia expert
#      clock:
#        power_grid_model.conversion.filters.get_clock:
#          - Clock    # cross reference type
#      tap_side: Tap side      # cross reference type
#      tap_pos: Tap
#      tap_min: Tap min        # cross reference type
#      tap_max: Tap max        # cross reference type
#      tap_nom: Tap nom        # cross reference type
#      tap_size: Tap size      # cross reference type
#      uk_min: uk              # cross reference type
#      uk_max: uk              # cross reference type
#      pk_min: Pk              # cross reference type
#      pk_max: Pk              # cross reference type
#      r_grounding_from: Re1      # kan alleen Re vinden
#      x_grounding_from: Xe1      # niet gevonden
#      r_grounding_to: Re2        # kan alleen Re vinden
#      x_grounding_to: Xe2        # niet gevonden
#      extra:
#        - Name
#        - ID
#
#  Sources:
#    source:
#      id:
#        - Node.Number
#        - Subnumber
#      node: Node.Number
#      status: Switch state
#      u_ref:
#        power_grid_model.conversion.filters.multiply:
#          - Uprofile
#          - urated
#      u_ref: Uref         # Uprofile / urated van node
#      sk: Sk"nom
#
#  Connections: # van connections naar loads, maak cable, node eind vd cable, load verbonden met de node bram vragen
#
#    line:
#      id:
#        - Node.Number
#        - Subnumber
#      from_node: Node.Number
#      to_node:
#        - Node.Number
#        - Subnumber
#    node:
#      id:
#        - Node.Number
#        - Subnumber
#    sym_load:
#      id:
#        - Node.Number      # niet gevonden
#        - Subnumber        # niet gevonden
#      node:
#        - Node.Number
#        - Subnumber
#      status: Switch state # niet gevonden
#      type: Behaviour      # niet gevonden
#      p_specified: Load.P
#      q_specified:
#        Load.Q
#      extra:
#        - Name
#        - ID     # niet gevonden

substitutions: #met bram doorlopen
  Switch state:
    'off': 'off'    #checken
    in: 'in'        #checken
  N1:
    none: false    #niet gevonden
    own: true      #niet gevonden
  N2:
    none: false    #niet gevonden
    own: true      #niet gevonden
  Behaviour: #niet gevonden
    Constant admittance: 1
    Constant impedance: 1
    ~Constant current: 2
    Constant power: 0
    Default: 0
    Industry: 0
    Business: 0
    Residential: 0
    Living: 0
  Tap side:
    '1': 1
    '2': 2
  Q: # Q-regeling? 0,1,2 gaia manual
    absorb: -1
    supply: 1
  Short type:
    4x50A: 50AL+25
