# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0
---
grid:
  Nodes:
    node:
      id:
        auto_id:
          key: Number
      u_rated: Unom
      extra:
        - ID
        - Name
  Cables:
    line:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: C
      tan1: 0
      r0: R0
      x0: X0
      c0: C0
      tan0: 0
      i_n: Inom'
      extra:
        - ID
        - Name
  Lines:
    line:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: C
      tan1: 0
      r0: R0
      x0: X0
      c0: C0
      tan0: 0
      i_n: Inom'
      extra:
        - ID
        - Name
  Links:
    link:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      extra:
        - ID
        - Name
  Reactance coils:
    line:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: 0
      tan1: 0
      r0: R0
      x0: X0
      c0: 0
      tan0: 0
      i_n: Inom
      extra:
        - ID
        - Name
  Transformers:
    transformer:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      i0:
        power_grid_model_io.functions.phase_to_phase.relative_no_load_current:
          i_0: Io
          p_0: Po
          s_nom: Snom
          u_nom: Unom2
      p0: Po
      winding_from:
        power_grid_model_io.functions.phase_to_phase.get_winding_from:
          conn_str: Connection
          neutral_grounding: N1
      winding_to:
        power_grid_model_io.functions.phase_to_phase.get_winding_to:
          conn_str: Connection
          neutral_grounding: N2
      clock:
        power_grid_model_io.functions.phase_to_phase.get_clock:
          conn_str: Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: Re1
      x_grounding_from: Xe1
      r_grounding_to: Re2
      x_grounding_to: Xe2
      extra:
        - ID
        - Name
  Special transformers:
    transformer:
      id:
        auto_id:
          key: Number
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          table: Nodes
          key:
            Number: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uknom
      pk: Pknom
      i0:
        power_grid_model_io.functions.phase_to_phase.relative_no_load_current:
          i_0: Io
          p_0: Po
          s_nom: Snom
          u_nom: Unom2
      p0: Po
      winding_from: 0
      winding_to: 0
      clock: 0
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: ukmin
      uk_max: ukmax
      pk_min: Pkmin
      pk_max: Pkmax
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - ID
        - Name
  Transformer loads:
    transformer:
      id:
        auto_id:
          name: transformer
          key:
            - Node.Number
            - Subnumber
      from_node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      to_node:
        auto_id:
          name: internal_node
          key:
            - Node.Number
            - Subnumber
      from_status: Switch state
      to_status: 1
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      p0: Po
      i0:
        power_grid_model_io.functions.phase_to_phase.relative_no_load_current:
          i_0: 0
          p_0: Po
          s_nom: Snom
          u_nom: Unom2
      winding_from:
        power_grid_model_io.functions.phase_to_phase.get_winding_from:
          conn_str: Connection
      winding_to:
        power_grid_model_io.functions.phase_to_phase.get_winding_to:
          conn_str: Connection
      clock:
        power_grid_model_io.functions.phase_to_phase.get_clock:
          conn_str: Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - ID
        - Name
    node:
      id:
        auto_id:
          name: internal_node
          key:
            - Node.Number
            - Subnumber
      u_rated: Unom2
      extra:
        - ID
        - Name
    sym_load:
      id:
        auto_id:
          name: load
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: internal_node
          key:
            - Node.Number
            - Subnumber
      status: Switch state
      type: Behaviour
      p_specified:
        multiply:
          - Load.P
          - reference:
              query_column: Node.Number
              other_table: Nodes
              key_column: Number
              value_column: Simultaneity
      q_specified:
        multiply:
          - Load.Q
          - reference:
              query_column: Node.Number
              other_table: Nodes
              key_column: Number
              value_column: Simultaneity
      extra:
        - ID
        - Name
    sym_gen:
      - id:
          auto_id:
            name: generation
            key:
              - Node.Number
              - Subnumber
        node:
          auto_id:
            name: internal_node
            key:
              - Node.Number
              - Subnumber
        status: Switch state
        type: 0
        p_specified: Generation.P
        q_specified: Generation.Q
        extra:
          - ID
          - Name
      - id:
          auto_id:
            name: pv_generation
            key:
              - Node.Number
              - Subnumber
        node:
          auto_id:
            name: internal_node
            key:
              - Node.Number
              - Subnumber
        status: Switch state
        type: 0
        p_specified: PV.Pnom
        q_specified:
          power_grid_model_io.functions.phase_to_phase.reactive_power:
            p: PV.Pnom
            cos_phi: 1
        extra:
          - ID
          - Name
  Sources:
    source:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      u_ref: Uref
      sk: Sk"nom
      rx_ratio: R/X
      z01_ratio: Z0/Z1
      extra:
        - ID
        - Name
  Synchronous generators:
    sym_gen:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      type: 0
      p_specified: Pref
      q_specified:
        multiply:
          - power_grid_model_io.functions.phase_to_phase.reactive_power:
              p: Pref
              cos_phi: cos phi
          - Q
      extra:
        - ID
        - Name
  Wind turbines:
    sym_gen:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      type: 1
      p_specified:
        power_grid_model_io.functions.value_or_default:
          value: Pref
          default:
            power_grid_model_io.functions.phase_to_phase.power_wind_speed:
              p_nom: Pnom
              wind_speed: Wind speed
      q_specified:
        power_grid_model_io.functions.phase_to_phase.reactive_power:
          p:
            power_grid_model_io.functions.value_or_default:
              value: Pref
              default:
                power_grid_model_io.functions.phase_to_phase.power_wind_speed:
                  p_nom: Pnom
                  wind_speed: Wind speed
          cos_phi: cos phi
      extra:
        - ID
        - Name
  Loads:
    sym_load:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      type: Behaviour
      p_specified:
        multiply:
          - P
          - reference:
              query_column: Node.Number
              other_table: Nodes
              key_column: Number
              value_column: Simultaneity
      q_specified:
        multiply:
          - Q
          - reference:
              query_column: Node.Number
              other_table: Nodes
              key_column: Number
              value_column: Simultaneity
      extra:
        - ID
        - Name
  Zigzag transformers:
    shunt:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      g1: 0
      b1: 0
      g0:
        power_grid_model_io.functions.complex_inverse_real_part:
          real: R0
          imag: X0
      b0:
        power_grid_model_io.functions.complex_inverse_imaginary_part:
          real: R0
          imag: X0
      extra:
        - ID
        - Name
  Capacitors:
    shunt:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      g1: 0
      b1:
        power_grid_model_io.functions.phase_to_phase.reactive_power_to_susceptance:
          q: Q
          u_nom: Unom
      g0: 0
      b0: 0
      extra:
        - ID
        - Name
  Reactors:
    shunt:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      g1: 0
      b1:
        multiply:
          - power_grid_model_io.functions.phase_to_phase.reactive_power_to_susceptance:
              q: Q
              u_nom: Unom
          - -1
      g0: 0
      b0: 0
      extra:
        - ID
        - Name
  Pvs:
    sym_gen:
      id:
        auto_id:
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          table: Nodes
          key:
            Number: Node.Number
      status: Switch state
      type: 0
      p_specified:
        multiply:
          - min:
              - Pnom
              - Inverter.Pnom | Inverter.Snom
          - Scaling
      q_specified:
        multiply:
          - power_grid_model_io.functions.phase_to_phase.reactive_power:
              p:
                min:
                  - Pnom
                  - Inverter.Pnom | Inverter.Snom
              cos_phi: Inverter.cos phi
          - Scaling
      extra:
        - ID
        - Name
units:
  A: null
  F:
    µF: 0.000_001
  V:
    kV: 1_000.0
  VA:
    kVA: 1_000.0
    MVA: 1_000_000.0
  VAR:
    kvar: 1_000.0
    Mvar: 1_000_000.0
  W:
    kW: 1_000.0
    MW: 1_000_000.0
  Wp:
    kWp: 1_000.0
    MWp: 1_000_000.0
  m/s: null
  ohm:
    Ohm: 1.0
  ohm/m:
    ohm/km: 0.001
  one:
    pu: 1.0
    "%": 0.01
    "‰": 0.001
substitutions:
  ".*Switch state":
    "off": 0
    "in": 1
  N1:
    none: false
    own: true
  N2:
    none: false
    own: true
  Behaviour:
    Constant admittance: 1
    Constant impedance: 1
    ~Constant current: 2
    Constant power: 0
    Default: 0
    Industry: 0
    Business: 0
    Residential: 0
    Living: 0
  Tap side:
    1: 0
    2: 1
  Synchronous generators.Q:
    absorb: -1
    supply: 1
