# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0
---
grid:
  Nodes:
    node:
      id:
        auto_id:
          name: Nodes
          key: Number
      u_rated: Unom
      extra: ID
  Cables:
    line:
      id:
        auto_id:
          name: Cables
          key: Number
      from_node:
        auto_id:
          name: Nodes
          key: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          name: Nodes
          key: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: C
      tan1: 0
      r0: R0
      x0: X0
      c0: C0
      tan0: 0
      i_n: Inom'
      extra:
        - Name
        - ID
  Links:
    link:
      id:
        auto_id:
          name: Links
          key: Number
      from_node:
        auto_id:
          name: Nodes
          key: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          name: Nodes
          key: To.Number
      to_status: To.Switch state
  Reactance coils:
    line:
      id:
        auto_id:
          name: Reactance coils
          key: Number
      from_node:
        auto_id:
          name: Nodes
          key: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          name: Nodes
          key: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: 0
      tan1: 0
      r0: R0
      x0: X0
      c0: 0
      tan0: 0
      i_n: Inom
      extra:
        - Name
        - ID
  Transformers:
    transformer:
      id:
        auto_id:
          name: Transformers
          key: From.Number
      from_node:
        auto_id:
          name: Nodes
          key: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          name: Nodes
          key: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - Io
          - Po
          - Snom
          - Unom2
      p0: Po
      winding_from:
        power_grid_model_io.filters.phase_to_phase.get_winding_from:
          - Connection
          - N1
      winding_to:
        power_grid_model_io.filters.phase_to_phase.get_winding_to:
          - Connection
          - N2
      clock:
        power_grid_model_io.filters.phase_to_phase.get_clock:
          - Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: Re1
      x_grounding_from: Xe1
      r_grounding_to: Re2
      x_grounding_to: Xe2
      extra:
        - Name
        - ID
  Special transformers:
    transformer:
      id:
        auto_id:
          name: Special transformers
          key: From.Number
      from_node:
        auto_id:
          name: Nodes
          key: From.Number
      from_status: From.Switch state
      to_node:
        auto_id:
          name: Nodes
          key: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uknom
      pk: Pknom
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - Io
          - Po
          - Snom
          - Unom2
      p0: Po
      winding_from: 0
      winding_to: 0
      clock: 0
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: ukmin
      uk_max: ukmax
      pk_min: Pkmin
      pk_max: Pkmax
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - Name
        - ID
  Transformer loads:
    transformer:
      id:
        auto_id:
          name:
            - Transformer loads
            - transformer
          key:
            - Node.Number
            - Subnumber
      from_node:
        auto_id:
          name: Nodes
          key: Node.Number
      to_node:
        auto_id:
          name:
            - Transformer loads
            - internal_node
          key:
            - Node.Number
            - Subnumber
      from_status: Switch state
      to_status: 1
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      p0: Po
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - 0
          - Po
          - Snom
          - Unom2
      winding_from:
        power_grid_model_io.filters.phase_to_phase.get_winding_from: Connection
      winding_to:
        power_grid_model_io.filters.phase_to_phase.get_winding_to: Connection
      clock:
        power_grid_model_io.filters.phase_to_phase.get_clock: Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - Name
        - ID
    node:
      id:
        auto_id:
          name:
            - Transformer loads
            - internal_node
          key:
            - Node.Number
            - Subnumber
      u_rated: Unom2
      extra: ID
    sym_load:
      id:
        auto_id:
          name:
            - Transformer loads
            - load
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name:
            - Transformer loads
            - internal_node
          key:
            - Node.Number
            - Subnumber
      status: Switch state
      type: Behaviour
      p_specified:
        power_grid_model_io.filters.multiply:
          - Load.P
          - Nodes!Simultaneity[Number=Node.Number]
      q_specified:
        power_grid_model_io.filters.multiply:
          - Load.Q
          - Nodes!Simultaneity[Number=Node.Number]
      extra:
        - Name
        - ID
    sym_gen:
      - id:
          auto_id:
            name:
              - Transformer loads
              - generation
            key:
              - Node.Number
              - Subnumber
        node:
          auto_id:
            name:
              - Transformer loads
              - internal_node
            key:
              - Node.Number
              - Subnumber
        status: Switch state
        type: 0
        p_specified: Generation.P
        q_specified: Generation.Q
        extra: Name
      - id:
          auto_id:
            name:
              - Transformer loads
              - pv_generation
            key:
              - Node.Number
              - Subnumber
        node:
          auto_id:
            name:
              - Transformer loads
              - internal_node
            key:
              - Node.Number
              - Subnumber
        status: Switch state
        type: 0
        p_specified: PV.Pnom
        q_specified:
          power_grid_model_io.filters.phase_to_phase.reactive_power:
            - PV.Pnom
            - 1
        extra: Name
  Sources:
    source:
      id:
        auto_id:
          name: Sources
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      u_ref: Uref
      sk: Sk"nom
      rx_ratio: R/X
      z01_ratio: Z0/Z1
  Synchronous generators:
    sym_gen:
      id:
        auto_id:
          name: Synchronous generators
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      type: 0
      p_specified: Pref
      q_specified:
        power_grid_model_io.filters.multiply:
          - power_grid_model_io.filters.phase_to_phase.reactive_power:
            - Pref
            - cos phi
          - Q
      extra: Name
  Wind turbines:
    sym_gen:
      id:
        auto_id:
          name: Wind turbines
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      type: 1
      p_specified:
        power_grid_model_io.filters.value_or_default:
          - Pref
          - power_grid_model_io.filters.phase_to_phase.power_wind_speed:
            - Pnom
            - Wind speed
      q_specified:
        power_grid_model_io.filters.phase_to_phase.reactive_power:
          - power_grid_model_io.filters.value_or_default:
            - Pref
            - power_grid_model_io.filters.phase_to_phase.power_wind_speed:
              - Pnom
              - Wind speed
          - cos phi
      extra: Name
  Loads:
    sym_load:
      id:
        auto_id:
          name: Loads
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      type: Behaviour
      p_specified:
        power_grid_model_io.filters.multiply:
          - P
          - Nodes!Simultaneity[Number=Node.Number]
      q_specified:
        power_grid_model_io.filters.multiply:
          - Q
          - Nodes!Simultaneity[Number=Node.Number]
      extra:
        - Name
        - ID
  Zigzag transformers:
    shunt:
      id:
        auto_id:
          name: Zigzag transformers
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      g1: 0
      b1: 0
      g0:
        power_grid_model_io.filters.complex_inverse_real_part:
          - R0
          - X0
      b0:
        power_grid_model_io.filters.complex_inverse_imaginary_part:
          - R0
          - X0
      extra:
        - Name
        - ID
  Pvs:
    sym_gen:
      id:
        auto_id:
          name: Pvs
          key:
            - Node.Number
            - Subnumber
      node:
        auto_id:
          name: Nodes
          key: Node.Number
      status: Switch state
      type: 0
      p_specified:
        min:
          - Pnom
          - Inverter.Pnom | Inverter.Snom
      q_specified:
        power_grid_model_io.filters.phase_to_phase.reactive_power:
          - min:
              - Pnom
              - Inverter.Pnom | Inverter.Snom
          - Inverter.cos phi
      extra: Name
units:
  A:
  F:
    µF: 0.000_001
  V:
    kV: 1_000.0
  VA:
    MVA: 1_000_000.0
  VAR:
    Mvar: 1_000_000.0
  W:
    kW: 1_000.0
    MW: 1_000_000.0
  Wp:
    MWp: 1_000_000.0
  m/s:
  ohm:
    Ohm: 1.0
  ohm/m:
    ohm/km: 0.001
  one:
    pu: 1.0
    "%": 0.01

substitutions:
  ".*Switch state":
    "off": 0
    "in": 1
  N1:
    none: false
    own: true
  N2:
    none: false
    own: true
  Behaviour:
    Constant admittance: 1
    Constant impedance: 1
    ~Constant current: 2
    Constant power: 0
    Default: 0
    Industry: 0
    Business: 0
    Residential: 0
    Living: 0
  Tap side:
    1: 0
    2: 1
  Synchronous generators.Q:
    absorb: -1
    supply: 1
