# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0
---
grid:
  Nodes:
    node: #1
      id: Number
      u_rated: Unom
      extra: ID
  Cables:
    line: #2
      id:
      - Number
      - 2
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: C
      tan1: 0
      r0: R0
      x0: X0
      c0: C0
      tan0: 0
      i_n: Inom'
      extra:
        - Name
        - ID
  Links:
    link: #3
      id:
        - Number
        - 3
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
  Reactance coils:
    line: #4
      id:
        - Number
        - 4
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
      r1: R
      x1: X
      c1: 0
      tan1: 0
      r0: R0
      x0: X0
      c0: 0
      tan0: 0
      i_n: Inom
      extra:
        - Name
        - ID
  Transformers:
    transformer: #5
      id:
        - Number
        - 5
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - Io
          - Po
          - Snom
          - Unom2
      p0: Po
      winding_from:
        power_grid_model_io.filters.phase_to_phase.get_winding_from:
          - Connection
          - N1
      winding_to:
        power_grid_model_io.filters.phase_to_phase.get_winding_to:
          - Connection
          - N2
      clock:
        power_grid_model_io.filters.phase_to_phase.get_clock:
          - Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: Re1
      x_grounding_from: Xe1
      r_grounding_to: Re2
      x_grounding_to: Xe2
      extra:
        - Name
        - ID
  Special transformers:
    transformer: #6
      id:
        - Number
        - 6
      from_node: From.Number
      from_status: From.Switch state
      to_node: To.Number
      to_status: To.Switch state
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uknom
      pk: Pknom
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - Io
          - Po
          - Snom
          - Unom2
      p0: Po
      winding_from: 0
      winding_to: 0
      clock: 0
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: ukmin
      uk_max: ukmax
      pk_min: Pkmin
      pk_max: Pkmax
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - Name
        - ID
  Transformer loads:
    transformer: #7
      id:
        - Node.Number
        - Subnumber
        - 7
      from_node: Node.Number
      to_node:
        - Node.Number
        - Subnumber
        - 8
      from_status: Switch state
      to_status: 1
      u1: Unom1
      u2: Unom2
      sn: Snom
      uk: uk
      pk: Pk
      p0: Po
      i0:
        power_grid_model_io.filters.phase_to_phase.relative_no_load_current:
          - 0
          - Po
          - Snom
          - Unom2
      winding_from:
        power_grid_model_io.filters.phase_to_phase.get_winding_from: Connection
      winding_to:
        power_grid_model_io.filters.phase_to_phase.get_winding_to: Connection
      clock:
        power_grid_model_io.filters.phase_to_phase.get_clock: Connection
      tap_side: Tap side
      tap_pos: Tap
      tap_min: Tap min
      tap_max: Tap max
      tap_nom: Tap nom
      tap_size: Tap size
      uk_min: uk
      uk_max: uk
      pk_min: Pk
      pk_max: Pk
      r_grounding_from: 0
      x_grounding_from: 0
      r_grounding_to: 0
      x_grounding_to: 0
      extra:
        - Name
        - ID
    node: #8
      id:
        - Node.Number
        - Subnumber
        - 8
      u_rated: Unom2
      extra: ID
    sym_load: #9
      id:
        - Node.Number
        - Subnumber
        - 9
      node:
        - Node.Number
        - Subnumber
        - 8
      status: Switch state
      type: Behaviour
      p_specified:
        power_grid_model_io.filters.multiply:
          - Load.P
          - Nodes!Simultaneity[Number=Node.Number]
      q_specified:
        power_grid_model_io.filters.multiply:
          - Load.Q
          - Nodes!Simultaneity[Number=Node.Number]
      extra:
        - Name
        - ID
    sym_gen:
      - id: #10
          - Node.Number
          - Subnumber
          - 10
        node:
          - Node.Number
          - Subnumber
          - 8
        status: Switch state
        type: 0
        p_specified: Generation.P
        q_specified: Generation.Q
        extra: Name
      - id: #11
          - Node.Number
          - Subnumber
          - 11
        node:
          - Node.Number
          - Subnumber
          - 8
        status: Switch state
        type: 0
        p_specified: PV.Pnom
        q_specified:
          power_grid_model_io.filters.phase_to_phase.reactive_power:
            - PV.Pnom
            - 1
        extra: Name
  Sources:
    source: #12
      id:
        - Node.Number
        - Subnumber
        - 12
      node: Node.Number
      status: Switch state
      u_ref: Uref
      sk: Sk"nom
      rx_ratio: R/X
      z01_ratio: Z0/Z1
  Synchronous generators:
    sym_gen: #13
      id:
        - Node.Number
        - Subnumber
        - 13
      node: Node.Number
      status: Switch state
      type: 0
      p_specified: Pref
      q_specified:
        power_grid_model_io.filters.multiply:
          - power_grid_model_io.filters.phase_to_phase.reactive_power:
            - Pref
            - cos phi
          - Q
      extra: Name
  Wind turbines:
    sym_gen: #14
      id:
        - Node.Number
        - Subnumber
        - 14
      node: Node.Number
      status: Switch state
      type: 1
      p_specified:
        power_grid_model_io.filters.value_or_default:
          - Pref
          - power_grid_model_io.filters.phase_to_phase.power_wind_speed:
            - Pnom
            - Wind speed
      q_specified:
        power_grid_model_io.filters.phase_to_phase.reactive_power:
          - power_grid_model_io.filters.value_or_default:
            - Pref
            - power_grid_model_io.filters.phase_to_phase.power_wind_speed:
              - Pnom
              - Wind speed
          - cos phi
      extra: Name
  Loads:
    sym_load: #15
      id:
        - Node.Number
        - Subnumber
        - 15
      node: Node.Number
      status: Switch state
      type: Behaviour
      p_specified:
        power_grid_model_io.filters.multiply:
          - P
          - Nodes!Simultaneity[Number=Node.Number]
      q_specified:
        power_grid_model_io.filters.multiply:
          - Q
          - Nodes!Simultaneity[Number=Node.Number]
      extra:
        - Name
        - ID
  Zigzag transformers:
    shunt: #16
      id:
        - Node.Number
        - Subnumber
        - 16
      node: Node.Number
      status: Switch state
      g1: 0
      b1: 0
      g0:
        power_grid_model_io.filters.complex_inverse_real_part:
          - R0
          - X0
      b0:
        power_grid_model_io.filters.complex_inverse_imaginary_part:
          - R0
          - X0
      extra:
        - Name
        - ID
  Pvs:
    sym_gen: #17
      id:
        - Node.Number
        - Subnumber
        - 17
      node: Node.Number
      status: Switch state
      type: 0
      p_specified:
        min:
          - Pnom
          - Inverter.Pnom | Inverter.Snom
      q_specified:
        power_grid_model_io.filters.phase_to_phase.reactive_power:
          - min:
              - Pnom
              - Inverter.Pnom | Inverter.Snom
          - Inverter.cos phi
      extra: Name
units:
  A:
  F:
    µF: 0.000001
  V:
    kV: 1000.0
  VA:
    MVA: 1000000.0
  VAR:
    Mvar: 1000000.0
  W:
    kW: 1000.0
    MW: 1000000.0
  Wp:
    MWp: 1000000.0
  m/s:
  ohm:
    Ohm: 1.0
  ohm/m:
    ohm/km: 0.001
  one:
    pu: 1.0
    "%": 0.01

substitutions:
  ".*Switch state":
    "off": 0
    "in": 1
  N1:
    none: false
    own: true
  N2:
    none: false
    own: true
  Behaviour:
    Constant admittance: 1
    Constant impedance: 1
    ~Constant current: 2
    Constant power: 0
    Default: 0
    Industry: 0
    Business: 0
    Residential: 0
    Living: 0
  Tap side:
    1: 0
    2: 1
  Synchronous generators.Q:
    absorb: -1
    supply: 1
