# SPDX-FileCopyrightText: Contributors to the Power Grid Model project <powergridmodel@lfenergy.org>
#
# SPDX-License-Identifier: MPL-2.0


name: Check Code Quality

on:
  # run pipeline from another workflow
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-code-quality
  cancel-in-progress: true

jobs:
  check-code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1

      - name: Install most linters from uv
        run: |
          uv sync --group lint

      - name: Run mypy
        run: |
          uv run --frozen mypy .

      - name: Run ruff
        run: |
          uv run --frozen ruff check .
          uv run --frozen ruff format .

      - name: If needed raise error
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            echo "Formatting not correct! See below the files which need to be reformatted!"
            git status --porcelain --untracked-files=no
            exit 1
          fi
